# Generated by Django 5.2.17 on 2026-09-15 06:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', help_text='Application role: STAFF, TEACHER, or STUDENT', max_length=20),
        ),
    ]
