# Generated by Django 5.2.17 on 2026-09-15 07:39

import accounts.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[accounts.validators.validate_email_custom]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Optional. Maximum 50 alphabetic characters.', max_length=50, validators=[accounts.validators.validate_name_custom]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Optional. Maximum 50 alphabetic characters.', max_length=50, validators=[accounts.validators.validate_name_custom]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional 10-digit Indian mobile number starting with 6, 7, 8, or 9.', max_length=15, null=True, validators=[accounts.validators.validate_indian_phone]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', help_text='Application role: STAFF, TEACHER, or STUDENT', max_length=20, validators=[accounts.validators.validate_role_custom]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 3-30 characters. Letters, numbers, underscore, and dot only.', max_length=30, unique=True, validators=[accounts.validators.validate_username_custom]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_lower_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_lower_username'),
        ),
    ]
