# Generated by Django 5.2.17 on 2026-09-16 08:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(help_text='Unique student registration/enrollment code', max_length=30, unique=True)),
                ('roll_number', models.CharField(help_text='Roll number within division (unique per division)', max_length=30)),
                ('admission_year', models.PositiveIntegerField(help_text='Year of admission (e.g. 2024)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('LEFT', 'Left')], default='ACTIVE', help_text='Current student status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Optional practical batch within the division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.practicalbatch')),
                ('division', models.ForeignKey(help_text='Division to which student belongs', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.division')),
                ('user', models.OneToOneField(help_text='Associated user account with STUDENT role', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['division', 'roll_number'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('student_code'), name='unique_lower_student_code'), models.UniqueConstraint(fields=('division', 'roll_number'), name='unique_roll_number_per_division')],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(help_text='Unique employee code for the teacher', max_length=30, unique=True)),
                ('designation', models.CharField(help_text='Designation (e.g. Professor, Assistant Professor, Lecturer)', max_length=100)),
                ('joining_date', models.DateField(blank=True, help_text='Date of joining the institution', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Current employment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department to which teacher belongs', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='academics.department')),
                ('user', models.OneToOneField(help_text='Associated user account with TEACHER role', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('employee_code'), name='unique_lower_employee_code')],
            },
        ),
    ]
