# Generated by Django 5.2.17 on 2026-09-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_teacherprofile'),
        ('accounts', '0004_user_email_verified_emailverification'),
    ]

    operations = [
    ]
