# Generated by Django 5.2.17 on 2026-09-15 07:59

import academics.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full department name (e.g., Computer Engineering)', max_length=150)),
                ('code', models.CharField(help_text='Unique department code (e.g., CS, MECH, IT)', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_lower_department_code')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full program name (e.g., Bachelor of Technology in Computer Science)', max_length=150)),
                ('code', models.CharField(help_text='Unique program code (e.g., BTECH-CS, BE-IT)', max_length=20, unique=True)),
                ('duration_years', models.PositiveSmallIntegerField(default=4, help_text='Program duration in years (e.g., 4 for B.Tech, 2 for M.Tech)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Parent department offering this program', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(help_text='Semester number (e.g., 1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('academic_year', models.CharField(help_text="Academic session in 'YYYY-YYYY' format (e.g., 2025-2026)", max_length=9, validators=[academics.validators.validate_academic_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(help_text='Parent program for this semester', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.program')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['academic_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Division/Section name (e.g., A, B, Div-1)', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=60, help_text='Maximum student capacity for this division (must be > 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(help_text='Parent semester for this division', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Subject title (e.g., Data Structures and Algorithms)', max_length=150)),
                ('code', models.CharField(help_text='Unique subject code (e.g., CS201, IT-302)', max_length=30, unique=True)),
                ('type', models.CharField(choices=[('LECTURE', 'Lecture'), ('PRACTICAL', 'Practical'), ('TUTORIAL', 'Tutorial')], default='LECTURE', help_text='Subject delivery type (LECTURE, PRACTICAL, or TUTORIAL)', max_length=20)),
                ('credits', models.DecimalField(decimal_places=1, default=3.0, help_text='Credit points assigned to this subject (>= 0)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weekly_lectures', models.PositiveSmallIntegerField(default=3, help_text='Number of lecture sessions per week (>= 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_practicals', models.PositiveSmallIntegerField(default=0, help_text='Number of practical/lab sessions per week (>= 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Standard duration of a single session in minutes (e.g., 60)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(help_text='Parent program offering this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.program')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PracticalBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Batch name (e.g., B1, B2, Batch-A)', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=20, help_text='Maximum student capacity for this practical batch (must be > 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(help_text='Parent division for this practical batch', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.division')),
            ],
            options={
                'verbose_name': 'Practical Batch',
                'verbose_name_plural': 'Practical Batches',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('division', 'name'), name='unique_division_batch_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_lower_program_code'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('program', 'number', 'academic_year'), name='unique_program_semester_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('semester', 'name'), name='unique_semester_division_name'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_lower_subject_code'),
        ),
    ]
