# Generated by Django 5.2.17 on 2026-09-16 11:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0004_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Assignment priority/preference rank (e.g., 1 = primary)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Assigned subject', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='academics.subject')),
                ('teacher', models.ForeignKey(help_text='Assigned teacher profile', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'ordering': ['teacher', 'priority', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject'), name='unique_teacher_subject_assignment')],
            },
        ),
    ]
