# Generated by Django 5.2.17 on 2026-09-16 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teacheravailability'),
        ('accounts', '0004_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Leave start date')),
                ('end_date', models.DateField(help_text='Leave end date')),
                ('reason', models.TextField(help_text='Reason for leave request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Leave request status (PENDING, APPROVED, REJECTED)', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Associated teacher profile', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher Leave',
                'verbose_name_plural': 'Teacher Leaves',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
