# Generated by Django 5.2.17 on 2026-09-16 12:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teacherleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building', models.CharField(help_text='Building name or code (e.g., Main Building, Block A)', max_length=50)),
                ('room_number', models.CharField(help_text='Room number/name (e.g., 101, LH-1)', max_length=20)),
                ('floor', models.IntegerField(default=0, help_text='Floor number (e.g., 0 for Ground, 1 for 1st Floor)')),
                ('capacity', models.PositiveIntegerField(default=60, help_text='Seating capacity (must be > 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', help_text='Classroom availability status (AVAILABLE, UNAVAILABLE, MAINTENANCE)', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['building', 'room_number'],
                'constraints': [models.UniqueConstraint(fields=('building', 'room_number'), name='unique_classroom_building_room')],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building', models.CharField(help_text='Building name or code (e.g., Tech Block, Block B)', max_length=50)),
                ('lab_number', models.CharField(help_text='Lab number/code (e.g., LAB-101, L1)', max_length=20)),
                ('name', models.CharField(help_text='Laboratory name (e.g., Computer Systems Lab, Physics Lab)', max_length=100)),
                ('floor', models.IntegerField(default=0, help_text='Floor number (e.g., 0 for Ground, 1 for 1st Floor)')),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Lab student capacity (must be > 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', help_text='Laboratory availability status (AVAILABLE, UNAVAILABLE, MAINTENANCE)', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
                'ordering': ['building', 'lab_number'],
                'constraints': [models.UniqueConstraint(fields=('building', 'lab_number'), name='unique_laboratory_building_lab')],
            },
        ),
    ]
