# Generated by Django 5.2.17 on 2026-09-17 06:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classroom_laboratory'),
        ('accounts', '0004_studentprofile_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='Academic year in YYYY-YYYY format (e.g. 2025-2026)', max_length=9)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this timetable configuration', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('REVIEW', 'Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current timetable lifecycle status', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, help_text='Timestamp when the timetable was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who created this timetable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(help_text='Semester for this timetable', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-academic_year', 'semester', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='Day of the week', max_length=15)),
                ('start_time', models.TimeField(help_text='Slot start time')),
                ('end_time', models.TimeField(help_text='Slot end time')),
                ('session_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('PRACTICAL', 'Practical'), ('TUTORIAL', 'Tutorial')], default='LECTURE', help_text='Type of academic session (LECTURE, PRACTICAL, TUTORIAL)', max_length=15)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', help_text='Slot status (SCHEDULED, CANCELLED, RESCHEDULED)', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Practical/Lab batch (if practical or batch-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='academics.practicalbatch')),
                ('classroom', models.ForeignKey(blank=True, help_text='Classroom allocated for lecture/tutorial session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='academics.classroom')),
                ('division', models.ForeignKey(help_text='Class division', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.division')),
                ('laboratory', models.ForeignKey(blank=True, help_text='Laboratory allocated for practical session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='academics.laboratory')),
                ('subject', models.ForeignKey(help_text='Subject/Course for this slot', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.subject')),
                ('teacher', models.ForeignKey(help_text='Assigned teacher', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='accounts.teacherprofile')),
                ('timetable', models.ForeignKey(help_text='Parent timetable', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ['timetable', 'day', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('semester', 'academic_year', 'version'), name='unique_semester_year_version_timetable'),
        ),
    ]
