# Generated by Django 5.2.17 on 2026-09-17 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_timetable_timetableslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('TEACHER_CLASH', 'Teacher Clash'), ('CLASSROOM_CLASH', 'Classroom Clash'), ('LAB_CLASH', 'Laboratory Clash'), ('DIVISION_CLASH', 'Division Clash'), ('BATCH_CLASH', 'Batch Clash')], help_text='Type of conflict detected', max_length=20)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', help_text='Severity level of the conflict', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of the clash/conflict')),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='DETECTED', help_text='Current conflict status', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the conflict was marked resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflicting_slot', models.ForeignKey(blank=True, help_text='Secondary timetable slot involved in this conflict', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_conflicts', to='academics.timetableslot')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Staff user who resolved this conflict', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, help_text='Primary timetable slot involved in this conflict', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='academics.timetableslot')),
                ('timetable', models.ForeignKey(help_text='Associated timetable', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='academics.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Conflict',
                'verbose_name_plural': 'Timetable Conflicts',
                'ordering': ['-severity', '-created_at'],
            },
        ),
    ]
