# Generated by Django 5.2.17 on 2026-09-17 12:52

from django.conf import settings
from django.db import migrations, models


def normalize_existing_conflicts(apps, schema_editor):
    TimetableConflict = apps.get_model('academics', 'TimetableConflict')
    conflicts = list(TimetableConflict.objects.all().order_by('created_at'))
    seen = {}
    to_delete_ids = []

    for c in conflicts:
        if c.slot_id and c.conflicting_slot_id and str(c.slot_id) > str(c.conflicting_slot_id):
            c.slot_id, c.conflicting_slot_id = c.conflicting_slot_id, c.slot_id

        key = (c.timetable_id, c.conflict_type, str(c.slot_id), str(c.conflicting_slot_id))
        if key in seen:
            existing = seen[key]
            if c.status in ("RESOLVED", "IGNORED") and existing.status == "DETECTED":
                to_delete_ids.append(existing.id)
                seen[key] = c
                c.save(update_fields=['slot_id', 'conflicting_slot_id'])
            else:
                to_delete_ids.append(c.id)
        else:
            seen[key] = c
            c.save(update_fields=['slot_id', 'conflicting_slot_id'])

    if to_delete_ids:
        TimetableConflict.objects.filter(id__in=to_delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_timetableconflict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_existing_conflicts, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='timetableconflict',
            constraint=models.UniqueConstraint(fields=('timetable', 'conflict_type', 'slot', 'conflicting_slot'), name='unique_timetable_conflict_pair'),
        ),
    ]

