# Generated by Django 5.2.17 on 2026-09-22 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_timetableconflict_unique_timetable_conflict_pair'),
        ('accounts', '0004_studentprofile_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for the substitution assignment')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text='Status of the substitution (PENDING, CONFIRMED, CANCELLED)', max_length=15)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the substitution was confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absent_teacher', models.ForeignKey(help_text='The original teacher who is absent', on_delete=django.db.models.deletion.CASCADE, related_name='absences_substituted', to='accounts.teacherprofile')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff user who confirmed the substitution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_substitutions', to=settings.AUTH_USER_MODEL)),
                ('substitute_teacher', models.ForeignKey(help_text='The assigned replacement teacher', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_assigned', to='accounts.teacherprofile')),
                ('teacher_leave', models.ForeignKey(blank=True, help_text='Associated approved leave request if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='academics.teacherleave')),
                ('timetable_slot', models.ForeignKey(help_text='The affected timetable slot', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='academics.timetableslot')),
            ],
            options={
                'verbose_name': 'Teacher Substitution',
                'verbose_name_plural': 'Teacher Substitutions',
                'ordering': ['-assigned_at', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('timetable_slot',), name='unique_active_substitution_per_slot')],
            },
        ),
    ]
