# Generated by Django 5.2.17 on 2026-09-23 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_teachersubstitution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubstitution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='CONFIRMED', help_text='Status of the substitution (PENDING, CONFIRMED, CANCELLED, DECLINED)', max_length=15),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('SUBSTITUTION_ASSIGNED', 'Substitution Assigned'), ('SUBSTITUTION_ACCEPTED', 'Substitution Accepted'), ('SUBSTITUTION_DECLINED', 'Substitution Declined'), ('GENERAL', 'General')], default='GENERAL', help_text='Type of notification', max_length=35)),
                ('title', models.CharField(help_text='Notification headline/title', max_length=255)),
                ('message', models.TextField(help_text='Notification message body')),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was marked as read', null=True)),
                ('recipient', models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_substitution', models.ForeignKey(blank=True, help_text='Associated substitution if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='academics.teachersubstitution')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
