# Generated by Django 5.2.17 on 2026-09-23 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_teachersubstitution_status_notification'),
        ('accounts', '0004_studentprofile_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotReschedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='New day of the week', max_length=15)),
                ('new_start_time', models.TimeField(help_text='New slot start time')),
                ('new_end_time', models.TimeField(help_text='New slot end time')),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for rescheduling')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text='Status of the reschedule (PENDING, CONFIRMED, CANCELLED)', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who confirmed the reschedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reschedules', to=settings.AUTH_USER_MODEL)),
                ('new_classroom', models.ForeignKey(blank=True, help_text='New classroom if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_slots', to='academics.classroom')),
                ('new_laboratory', models.ForeignKey(blank=True, help_text='New laboratory if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_slots', to='academics.laboratory')),
                ('new_teacher', models.ForeignKey(help_text='The newly assigned teacher (can be same or different)', on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_slots', to='accounts.teacherprofile')),
                ('new_timetable', models.ForeignKey(blank=True, help_text='New draft timetable version created for this reschedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_changes', to='academics.timetable')),
                ('original_slot', models.ForeignKey(help_text='The original timetable slot being rescheduled', on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='academics.timetableslot')),
            ],
            options={
                'verbose_name': 'Slot Reschedule',
                'verbose_name_plural': 'Slot Reschedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
