# Generated by Django 5.2.17 on 2026-09-23 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_slotreschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('TIMETABLE_CREATED', 'Timetable Created'), ('TIMETABLE_GENERATED', 'Timetable Generated'), ('TIMETABLE_PUBLISHED', 'Timetable Published'), ('TIMETABLE_ARCHIVED', 'Timetable Archived'), ('SLOT_CREATED', 'Slot Created'), ('SLOT_UPDATED', 'Slot Updated'), ('SLOT_CANCELLED', 'Slot Cancelled'), ('SLOT_RESCHEDULED', 'Slot Rescheduled'), ('SUBSTITUTE_ASSIGNED', 'Substitute Assigned'), ('SUBSTITUTE_ACCEPTED', 'Substitute Accepted'), ('SUBSTITUTE_DECLINED', 'Substitute Declined')], help_text='Audit action type', max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Reason or description for the change', null=True)),
                ('old_data', models.JSONField(blank=True, help_text='Snapshot of previous data before change', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Snapshot of new data after change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_change_logs', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(help_text='Timetable associated with this log entry', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='academics.timetable')),
                ('timetable_slot', models.ForeignKey(blank=True, help_text='Timetable slot associated with this log entry (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='academics.timetableslot')),
            ],
            options={
                'verbose_name': 'Timetable Change Log',
                'verbose_name_plural': 'Timetable Change Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
